-- 卡牌类型枚举
CARD_TYPE_ATTRIBUTE = 0  -- 属性卡
CARD_TYPE_SPELL = 1      -- 魔法卡
CARD_TYPE_MINION = 2     -- 单位卡
CARD_TYPE_EQUIPMENT = 4     -- 装备卡

-- 卡牌施法类型枚举
CARD_BEHAVIOR_NO_TARGET = 0       -- 无目标
CARD_BEHAVIOR_SINGLE_TARGET = 1   -- 单体目标
CARD_BEHAVIOR_POINT = 2           -- 点目标，所有的召唤单位的卡牌都是点目标卡牌

-- 卡牌的释放时机
CARD_CASTTIME_MY_ROUND = 0 -- 只能在本方回合使用
CARD_CASTTIME_ENEMY_ROUND = 1 -- 只能在敌方回合使用
CARD_CASTTIME_BOTH = 2 -- 双方回合（任意时间都可以使用）

-- 卡牌的释放位置
CARD_CAST_POSITION_MY_FIELD = 0 -- 只能在本方半场使用
CARD_CAST_POSITION_ENEMY_FIELD = 1 -- 只能在敌方半场使用
CARD_CAST_POSITION_BOTH = 2 -- 可以在场地的任意位置使用

-- 卡牌的主属性
ATTRIBUTE_NONE = 0 -- 无属性
ATTRIBUTE_STRENGTH = 1 -- 力量
ATTRIBUTE_AGILITY = 2 -- 敏捷
ATTRIBUTE_INTELLECT = 3 -- 智力

-- 回合阶段
TURN_PHASE_STRATEGY = 0 -- 策略阶段
TURN_PHASE_BATTLE = 1 -- 战斗阶段
TURN_PHASE_POST_BATTLE = 2 -- 战斗后阶段

-- 区域属性
BATTLEFIELD_AREA_MY_BASE = 0
BATTLEFIELD_AREA_LINE = 1
BATTLEFIELD_AREA_ENEMY_BASE = 2

-- 选择器类型
SELECTOR_POINT = 0
SELECTOR_UNIT = 1
SELECTOR_NUMBER = 2
SELECTOR_YESNO = 3

-- 执行结果
EFFECT_RESULT_SUCCESS = nil -- 默认返回为空
EFFECT_RESULT_DONT_DISCARD_CARD = 1 -- 不弃牌
EFFECT_RESULT_DONT_SPEND_MANA = 2 -- 不消耗

-- 使用实际
TIMING_NORMAL = 0
TIMING_INSTANT = 1

